services:
  nextjs:
    environment:
      WATCHPACK_POLLING: true
      ENVIRONMENT: dev
      # - NEXT_PUBLIC_SITE_NAME: sol
      # - NEXT_PUBLIC_SITE_BASE_DOMAIN: http://localhost
    build:
      target: dev
    volumes:
      - ./nextjs:/app
      - /app/node_modules
  nginx:
    build:
      target: dev
  worker:
    environment:
      ENVIRONMENT: dev
  scheduler:
    environment:
      ENVIRONMENT: dev

  django:
    volumes:
      - ./web:/app
    environment:
      ENVIRONMENT: dev
      # SITE_DOMAIN: localhost
      # SECRET_KEY: sfsado947u234hhjsdlfqsadf
      # NEXT_PUBLIC_SITE_NAME: sol
      # NEXT_PUBLIC_SITE_BASE_DOMAIN: http://localhost
      # DJANGO_SETTINGS_MODULE: settings
      # POSTGRES_DB: soldb
      # POSTGRES_USER: soluser
      # POSTGRES_PASSWORD: solsecretpass
      # REDIS_PASSWORD: solsecretpassredis
      # REDIS_HOST: redis
      # EMAIL_HOST: smtp.sendgrid.net
      # EMAIL_HOST_USER: thatcher@grav.solutions
      # PUBLIC_API: False
      # SENTRY_DSN: https://41ef1b7c8933eff59d081bbb720fb5b8@o4508878567440389.ingest.us.sentry.io/4508878589657088
    build:
      target: dev
