volumes:
  pgdata:

services:
  nextjs:
    restart: always
    depends_on:
      - django
    build:
      context: ./nextjs
    expose:
      - 3000
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  django:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./django
    expose:
      - 8000
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    depends_on:
      - django
      - nextjs
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
