volumes:
  pgdata:

services:
  nextjs:
    restart: always
    depends_on:
      - django
    build:
      context: ./nextjs
      args: 
        - BUILD_ENV=dev
    expose:
      - 3000
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  django:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./django
      args: 
        - BUILD_ENV=dev
    expose:
      - 8000
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    depends_on:
      - django
      - nextjs
    build:
      context: ./nginx
      args: 
        - BUILD_ENV=dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    image: postgres:12.0-alpine
    healthcheck:
      interval: 5s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      timeout: 5s
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .prod.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
