services:
  nextjs:
    build:
      args:
        - BUILD_ENV=prod
  django:
    build:
      args:
        - BUILD_ENV=prod
  nginx:
    build:
      args:
        - BUILD_ENV=prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
