volumes:
  pgdata:

services:
  nextjs:
    container_name: newsolwebapp-web-nextjs
    restart: always
    build:
      context: ./nextjs
      dockerfile: Dockerfile.nextjs
      target: dev
    expose:
      - 3000
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    environment:
      ENVIRONMENT: dev
      NEXT_PUBLIC_SITE_NAME: sol
      NEXT_PUBLIC_SITE_BASE_DOMAIN: http://localhost
    depends_on:
      - django
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nextjs:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  django:
    container_name: newsolwebapp-web-django
    restart: always
    build:
      context: ./django
      dockerfile: Dockerfile.django
      target: dev
    image: newsolwebapp-django:dev
    expose:
      - 8000
    environment:
      ENVIRONMENT: dev
      SITE_DOMAIN: localhost
      SECRET_KEY: sfsado947u234hhjsdlfqsadf
      NEXT_PUBLIC_SITE_BASE_DOMAIN: http://localhost
      DJANGO_SETTINGS_MODULE: settings
      POSTGRES_DB: soldb
      POSTGRES_USER: soluser
      POSTGRES_PASSWORD: solsecretpass
      REDIS_PASSWORD: solsecretpassredis
      REDIS_HOST: redis
      EMAIL_HOST:
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
    depends_on:
      - postgres
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://django:8000/api/healthcheck/ || exit 1
      interval: 30s
      retries: 5
      timeout: 5s
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: newsolwebapp-web-nginx
    restart: always
    depends_on:
      - django
      - nextjs
    build:
      context: .
      dockerfile: Dockerfile.nginx
      target: dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./django/static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: newsolwebapp-web-postgres
    restart: always
    image: postgres:12.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soluser -d soldb"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: soldb
      POSTGRES_USER: soluser
      POSTGRES_PASSWORD: solsecretpass
    logging:
      options:
        max-size: "10m"
        max-file: "3"
