volumes:
  pgdata:
  redis_data:

services:
  nextjs:
    container_name: sol-web-nextjs
    restart: always
    build:
      context: ./nextjs
    expose:
      - 3000
    volumes:
      - ./nextjs/public:/app/public
      - ./nextjs/src:/app/src
    env_file:
      - .env
    depends_on:
      - django
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nextjs:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  django:
    container_name: sol-web-django
    restart: always
    build:
      context: ./django
    expose:
      - 8000
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - postgres
      - scheduler
      - worker
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://django:8000/api/admin/ || exit 1
      interval: 30s
      retries: 5
      timeout: 5s
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: sol-web-nginx
    restart: always
    depends_on:
      - django
      - nextjs
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: sol-web-postgres
    restart: always
    image: postgres:12.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: sol-web-redis
    restart: always
    image: redis:6
    command: >
      --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  scheduler:
    container_name: sol-web-scheduler
    build:
      context: ./django
    restart: always
    volumes:
      - ./logs:/app/logs
    command: python manage.py rqscheduler --queue default
    env_file:
      - .env
    depends_on:
      - redis
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://scheduler:8000/api/admin/ || exit 1
      interval: 5m
      retries: 1
      timeout: 5s
      start_period: 30s

  worker:
    container_name: sol-web-worker
    build:
      context: ./django
    restart: always
    command: python manage.py rqworker default
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://worker:8000/api/admin/ || exit 1
      interval: 5m
      retries: 1
      timeout: 5s
      start_period: 30s
