volumes:
  redisdata:
services:
  redis:
    restart: always
    image: redis:6
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  scheduler:
    restart: always
    command: python manage.py rqscheduler --queue default
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    restart: always
    command: python manage.py rqworker default
    env_file:
      - .env
    depends_on:
      - redis
