FROM nginx:1.15-alpine AS base

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY .env /etc/nginx/.env

COPY ./django/static /app/static

FROM base AS dev

COPY ./nginx/dev /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]

FROM base AS prod

COPY ./nginx/prod /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
