services:
  nextjs:
    build:
      target: prod
  django:
    env_file:
      - .env
    build:
      target: prod
  nginx:
    build:
      target: prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
