FROM nginx:1.15-alpine

ARG BUILD_ENV=dev

COPY ./nginx/${BUILD_ENV} /etc/nginx/conf.d/
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY .env /etc/nginx/.env

# replace "$SITE_DOMAIN" with the value from the .env file
RUN export $(grep -v "^#" /etc/nginx/.env | xargs) && \
    for file in /etc/nginx/conf.d/*.conf /etc/nginx/nginx.conf; do \
        sed -i "s/\$SITE_DOMAIN/$SITE_DOMAIN/g" $file; \
    done


CMD ["nginx", "-g", "daemon off;"]
