FROM node:21-alpine

WORKDIR /app

COPY ./nextjs /app/nextjs
COPY package.json /app
COPY package-lock.json /app
COPY tailwind.config.js /app
COPY input.css /app

RUN npm install -D tailwindcss@latest

CMD npx tailwindcss -i input.css -o ./nextjs/public/static/css/styles.css --watch --poll
