volumes:
  pgdata:

services:
  nextjs:
    container_name: newsolwebapp-web-nextjs
    restart: unless-stopped
    build:
      context: ./nextjs
      dockerfile: Dockerfile.nextjs
      target: dev
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      django:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://nextjs:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  django:
    container_name: newsolwebapp-web-django
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile.django
    image: newsolwebapp-django:dev
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: newsolwebapp-web-nginx
    restart: unless-stopped
    depends_on:
      - django
      - nextjs
    build:
      context: .
      dockerfile: Dockerfile.nginx
      target: dev
    ports:
      - 80:80
      - 443:443
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: newsolwebapp-web-postgres
    restart: unless-stopped
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soluser -d soldb"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: soldb
    #   POSTGRES_USER: soluser
    #   POSTGRES_PASSWORD: solsecretpass
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: newsolwebapp-redis
    restart: unless-stopped
    image: redis:7-alpine
    command: >
      --requirepass solsecretpassredis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "solsecretpassredis", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - .env
    # environment:
    #   REDIS_PASSWORD: solsecretpassredis
    #   REDIS_HOST: redis
  scheduler:
    container_name: newsolwebapp-scheduler
    image: newsolwebapp-django:dev
    restart: unless-stopped
    command: celery -A celeryapp.celery:app beat -S redbeat.RedBeatScheduler --loglevel=info
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_healthy
    # environment:
    #   REDIS_PASSWORD: solsecretpassredis
    #   REDIS_HOST: redis
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    container_name: newsolwebapp-worker
    image: newsolwebapp-django:dev
    restart: unless-stopped
    command: celery -A celeryapp.celery:app worker --loglevel=info
    depends_on:
      django:
        condition: service_healthy
    env_file:
      - .env
    # environment:
    #   REDIS_PASSWORD: solsecretpassredis
    #   REDIS_HOST: redis
