volumes:
  pgdata:
  static:

services:
  nextjs:
    restart: always
    build:
      context: ./nextjs
    expose:
      - 3000
    volumes:
      - ./nextjs/public:/app/public
      - ./nextjs/src:/app/src
    env_file:
      - .env
    depends_on:
      - django
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  django:
    restart: always
    build:
      context: ./django
    expose:
      - 8000
    volumes:
      - static:/app/static
    env_file:
      - .env
    depends_on:
      - postgres
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    depends_on:
      - django
      - nextjs
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/app/static:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    image: postgres:12.0-alpine
    healthcheck:
      interval: 5s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      timeout: 5s
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
