services:
  nextjs:
    build:
      target: prod
  django:
    env_file:
      - .env
    environment:
      EMAIL_HOST: smtp.sendgrid.net
      EMAIL_HOST_USER: thatcher@grav.solutions
    build:
      target: prod
  nginx:
    build:
      target: prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
