{{- if .Values.celeryBeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol-web.fullname" . }}-celery-beat
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: 1  # MUST be 1 to avoid duplicate scheduled tasks
  strategy:
    type: Recreate  # Ensure only one instance runs at a time
  selector:
    matchLabels:
      {{- include "sol-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "sol-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sol-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: celery-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          command: ["celery", "-A", "celeryapp.celery:app", "beat", "-S", "redbeat.RedBeatScheduler", "--loglevel=info"]
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "sol-web.fullname" . }}-config
            - secretRef:
                name: {{ include "sol-web.fullname" . }}-secret
          env:
            - name: POSTGRES_HOST
              value: {{ include "sol-web.postgresql.fullname" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.postgresql.secretName" . }}
                  key: password
            - name: REDIS_HOST
              value: {{ include "sol-web.redis.fullname" . }}-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.redis.secretName" . }}
                  key: redis-password
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
