apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sol-web.fullname" . }}-config
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
data:
  # Global environment variables
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  SITE_DOMAIN: {{ .Values.global.siteDomain | quote }}
  NEXT_PUBLIC_SITE_NAME: {{ .Values.global.siteName | quote }}
  NEXT_PUBLIC_SITE_BASE_DOMAIN: {{ .Values.global.siteBaseDomain | quote }}

  # Django settings
  DJANGO_SETTINGS_MODULE: {{ .Values.django.env.DJANGO_SETTINGS_MODULE | quote }}
  PUBLIC_API: {{ .Values.django.env.PUBLIC_API | quote }}

  # Database settings
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}

  # Email settings
  EMAIL_HOST: {{ .Values.email.host | quote }}
  EMAIL_PORT: {{ .Values.email.port | quote }}
  EMAIL_USE_TLS: {{ .Values.email.useTLS | quote }}
  EMAIL_HOST_USER: {{ .Values.email.user | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.email.from | quote }}

  # Stripe settings (public keys only)
  {{- if .Values.django.secretEnv.STRIPE_SECRET_KEY }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.django.secretEnv.STRIPE_PUBLISHABLE_KEY | default "" | quote }}
  {{- end }}
