{{- if and .Values.django.enabled .Values.django.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sol-web.fullname" . }}-django
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sol-web.fullname" . }}-django
  minReplicas: {{ .Values.django.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.django.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.django.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.django.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.django.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.django.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
