{{- if .Values.django.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sol-web.fullname" . }}-django
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sol-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: django
{{- end }}
