{{- if .Values.django.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol-web.fullname" . }}-django
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  {{- if not .Values.django.autoscaling.enabled }}
  replicas: {{ .Values.django.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sol-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: django
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "sol-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: django
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sol-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: {{ include "sol-web.fullname" . }}-config
            - secretRef:
                name: {{ include "sol-web.fullname" . }}-secret
          env:
            - name: POSTGRES_HOST
              value: {{ include "sol-web.postgresql.fullname" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.postgresql.secretName" . }}
                  key: password
            - name: REDIS_HOST
              value: {{ include "sol-web.redis.fullname" . }}-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.redis.secretName" . }}
                  key: redis-password
        - name: collectstatic
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - configMapRef:
                name: {{ include "sol-web.fullname" . }}-config
            - secretRef:
                name: {{ include "sol-web.fullname" . }}-secret
          env:
            - name: POSTGRES_HOST
              value: {{ include "sol-web.postgresql.fullname" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.postgresql.secretName" . }}
                  key: password
            - name: REDIS_HOST
              value: {{ include "sol-web.redis.fullname" . }}-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.redis.secretName" . }}
                  key: redis-password
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: static-files
              mountPath: /app/static
          {{- end }}
      containers:
        - name: django
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.django.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.django.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.django.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.django.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.django.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.django.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.django.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.django.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.django.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.django.failureThreshold }}
          resources:
            {{- toYaml .Values.django.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "sol-web.fullname" . }}-config
            - secretRef:
                name: {{ include "sol-web.fullname" . }}-secret
          env:
            - name: POSTGRES_HOST
              value: {{ include "sol-web.postgresql.fullname" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.postgresql.secretName" . }}
                  key: password
            - name: REDIS_HOST
              value: {{ include "sol-web.redis.fullname" . }}-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sol-web.redis.secretName" . }}
                  key: redis-password
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: {{ include "sol-web.fullname" . }}-static
        - name: media-files
          persistentVolumeClaim:
            claimName: {{ include "sol-web.fullname" . }}-media
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
