{{- if .Values.nextjs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sol-web.fullname" . }}-nextjs
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: nextjs
spec:
  type: {{ .Values.nextjs.service.type }}
  ports:
    - port: {{ .Values.nextjs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sol-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nextjs
{{- end }}
