{{- if .Values.nextjs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol-web.fullname" . }}-nextjs
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: nextjs
spec:
  {{- if not .Values.nextjs.autoscaling.enabled }}
  replicas: {{ .Values.nextjs.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sol-web.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nextjs
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "sol-web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nextjs
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sol-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nextjs
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nextjs.image.repository }}:{{ .Values.nextjs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nextjs.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.nextjs.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.nextjs.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.nextjs.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.nextjs.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.nextjs.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.nextjs.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.nextjs.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.nextjs.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.nextjs.timeoutSeconds }}
            failureThreshold: {{ .Values.healthcheck.nextjs.failureThreshold }}
          resources:
            {{- toYaml .Values.nextjs.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "sol-web.fullname" . }}-config
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "sol-web.fullname" . }}-django:{{ .Values.django.service.port }}"
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
