{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sol-web.fullname" . }}-nginx
  labels:
    {{- include "sol-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.nginx.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "sol-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
