apiVersion: v2
name: sol-web
description: A Helm chart for sol-web
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - django
  - nextjs
  - postgres
  - redis
  - nginx
home: https://github.com/nov-solutions/sol-web
sources:
  - https://github.com/nov-solutions/sol-web
maintainers:
  - name: Thatcher Thornberry
    email: thatcher@grav.solutions
dependencies:
  - name: postgresql
    version: "~13.2.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "~18.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
