# values.local.yaml
global:
  environment: development
  siteName: sol-local
  siteBaseDomain: http://localhost
  siteDomain: localhost

# Use local images with Minikube
django:
  image:
    repository: sol-web-django
    pullPolicy: Never  # Important for Minikube local images
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
  env:
    DJANGO_SETTINGS_MODULE: settings
    DEBUG: "True"

nextjs:
  image:
    repository: sol-web-nextjs
    pullPolicy: Never
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false

nginx:
  image:
    repository: sol-web-nginx
    pullPolicy: Never
    tag: "latest"
  replicaCount: 1
  service:
    type: LoadBalancer  # Minikube will provide external IP

celeryWorker:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

celeryBeat:
  replicaCount: 1

# Reduce resources for local development
postgresql:
  primary:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      size: 1Gi

redis:
  master:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    persistence:
      size: 1Gi

# Disable ingress for simplicity (use LoadBalancer instead)
ingress:
  enabled: false

# Fix health check endpoints
healthcheck:
  django:
    path: /api/healthcheck/
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Override security context for development
podSecurityContext:
  fsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    drop: []
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0