apiVersion: apps/v1
kind: Deployment
metadata:
  name: sol-web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: django
          image: gcr.io/commanding-bee-443615-n7/sol-web-django:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: sol-web-secret
        - name: nextjs
          image: gcr.io/commanding-bee-443615-n7/sol-web-nextjs:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: sol-web-secret
        - name: nginx
          image: gcr.io/commanding-bee-443615-n7/sol-web-nginx:latest
          ports:
            - containerPort: 80
        - name: postgres
          image: postgres:13
          envFrom:
            - secretRef:
                name: sol-web-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
