

FROM node:21-alpine

WORKDIR /app

COPY . .

RUN npm i tailwindcss

# remove /app/public/static/css/styles.css if it exists
RUN rm -f /app/public/static/css/styles.css

CMD sh -c "npx tailwindcss -i /app/public/static/css/input.css -o /app/public/static/css/styles.css --watch --poll || echo 'Command failed!' && sleep 3600"
