name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      # - name: Minify CSS
      #   run: |
      #     cd ./nextjs
      #     npm ci
      #     npx tailwindcss -i ./public/static/css/input.css -o ./public/static/css/styles.css --minify

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=sol" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=https://sol.grav.solutions" >> .env
          echo "SITE_DOMAIN=sol" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Create Django static directory
        run: |
          cd ./django
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "latest"
          project_id: commanding-bee-443615-n7
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          echo "Y" | gcloud auth configure-docker

      - name: Build and push Next.js Docker image
        run: |
          cd ./nextjs
          docker build -t gcr.io/commanding-bee-443615-n7/commissary-web-nextjs:latest .
          docker push gcr.io/commanding-bee-443615-n7/commissary-web-nextjs:latest

      - name: Build and push Django Docker image
        run: |
          cd ./django
          docker build -t gcr.io/commanding-bee-443615-n7/commissary-web-django:latest .
          docker push gcr.io/commanding-bee-443615-n7/commissary-web-django:latest
      - name: Build and push Nginx image
        run: |
          docker build -t gcr.io/commanding-bee-443615-n7/commissary-web-nginx:latest .
          docker push gcr.io/commanding-bee-443615-n7/commissary-web-nginx:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials primary-cluster --zone us-central1
          kubectl apply -f terraform/k8s/kompose.yaml
          kubectl rollout restart deployment commissary-web
