name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Minify CSS
        run: |
          cd ./nextjs
          npm ci
          npx tailwindcss -i ./public/static/css/input.css -o ./public/static/css/styles.css --minify

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=sol" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=https://sol.grav.solutions" >> .env
          echo "SITE_DOMAIN=sol" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Create Django static directory
        run: |
          cd ./django
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "latest"
          project_id: commanding-bee-443615-n7

      - name: gcloud auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/865656196371/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "grav-sa@commanding-bee-443615-n7.iam.gserviceaccount.com"

      - name: test
        run: |
          gcloud auth list
          gcloud config list
          gcloud auth configure-docker

      # - name: Configure Docker to use gcloud as a credential helper
      #   run: |
      #     gcloud auth configure-docker

      # - name: Build and push Next.js Docker image
      #   run: |
      #     cd ./nextjs
      #     docker build -t gcr.io/commanding-bee-443615-n7/sol-web-nextjs:latest .
      #     docker push gcr.io/commanding-bee-443615-n7/sol-web-nextjs:latest

      # - name: Build and push Django Docker image
      #   run: |
      #     cd ./django
      #     docker build -t gcr.io/commanding-bee-443615-n7/sol-web-django:latest .
      #     docker push gcr.io/commanding-bee-443615-n7/sol-web-django:latest

      # - name: Deploy to GKE
      #   run: |
      #     gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl apply -f k8s/service.yaml
      #     kubectl apply -f k8s/ingress.yaml
