name: Deploy

on:
  push:
    branches:
      # TODO: migrate branching system to release branches
      - develop
      - main # TODO: change to master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up workflow with Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Set environment variables
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "SERVER_IP=54.149.89.23" >> $GITHUB_ENV
            echo "SSH_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          else
            echo "SERVER_IP=54.213.48.72" >> $GITHUB_ENV
            echo "SSH_KEY=${{ secrets.DEV_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          fi

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=raiquun" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=https://raiquun.com" >> .env
          echo "SITE_DOMAIN=raiquun.com" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "HEROKU_API_CLIENT_ID=${{ secrets.HEROKU_API_CLIENT_ID }}" >> .env
          echo "HEROKU_API_CLIENT_SECRET=${{ secrets.HEROKU_API_CLIENT_SECRET }}" >> .env
          echo "TEST_USER_ID=${{ secrets.TEST_USER_ID }}" >> .env
          echo "TEST_REFRESH_TOKEN=${{ secrets.TEST_REFRESH_TOKEN }}" >> .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env

      - name: Create Django static directory
        run: |
          cd ./django
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Expose SSH key
        run: |
          echo "${{ env.SSH_KEY }}" > deploy-key.pem
          chmod 400 deploy-key.pem

      - name: Sync files with server
        run: |
          rsync -r --delete --progress --exclude-from=exclude.txt -e "ssh -i $(pwd)/deploy-key.pem -o StrictHostKeyChecking=no" . ubuntu@${{ env.SERVER_IP }}:app

      - name: SSH into server; rebuild Docker containers
        run: |
          ssh -i $(pwd)/deploy-key.pem ubuntu@${{ env.SERVER_IP }} 'cd app && docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build -d'

      - name: Remove SSH key
        run: |
          rm -f deploy-key.pem

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set Docker image tag
        id: set-tag
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push Next.js Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nextjs
          push: true
          tags: ghcr.io/${{ github.repository }}/nextjs:${{ env.TAG }}

      - name: Build and push Nginx Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/nginx:${{ env.TAG }}

      - name: Build and push Django Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./django
          push: true
          tags: ghcr.io/${{ github.repository }}/django:${{ env.TAG }}
