name: Deploy

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up workflow with Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Minify CSS
        run: |
          cd ./nextjs
          npm ci
          npx tailwindcss -i ./public/static/css/input.css -o ./public/static/css/styles.css --minify

      - name: Expose SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > NEWSOLWEBAPP-web.pem
          chmod 400 NEWSOLWEBAPP-web.pem

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "SITE_NAME=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=TODO" >> .env
          echo "SITE_DESCRIPTION=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_DESCRIPTION=TODO" >> .env
          echo "SITE_TAGLINE=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_TAGLINE=TODO" >> .env
          echo "SITE_BASE_DOMAIN=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=TODO" >> .env
          echo "SITE_DOMAIN=TODO" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Sync files with server
        run: |
          rsync -r --delete --progress --exclude-from=exclude.txt -e "ssh -i $(pwd)/NEWSOLWEBAPP-web.pem -o StrictHostKeyChecking=no" . ubuntu@TODOipaddress:app

      - name: SSH into server; rebuild Docker containers
        run: |
          ssh -i $(pwd)/NEWSOLWEBAPP-web.pem ubuntu@TODOipaddress 'cd app && docker compose up --build -d'

      - name: Remove SSH key
        run: |
          rm -f NEWSOLWEBAPP-web.pem
