name: Test Django

on:
  pull_request:
    branches:
      - master

jobs:
  test-django:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "SITE_NAME=TODO" >> .env
          echo "SITE_DESCRIPTION=TODO" >> .env
          echo "SITE_TAGLINE=TODO" >> .env
          echo "SITE_DOMAIN=TODO" >> .env
          echo "SITE_BASE_DOMAIN=TODO" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "HEROKU_OAUTH_SECRET=${{ secrets.HEROKU_OAUTH_SECRET }}" >> .env
          echo "HEROKU_API_CLIENT_ID=${{ secrets.HEROKU_API_CLIENT_ID }}" >> .env
          echo "HEROKU_API_CLIENT_SECRET=${{ secrets.HEROKU_API_CLIENT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_SITE_DOMAIN=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=TODO" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=TODO" >> .env

      - name: Build Docker containers
        run: |
          docker compose up --build -d

      - name: Run tests
        run: |
          # Run your tests or other commands here
          echo "Tests or other tasks run here"

      - name: Bring down Docker containers
        run: docker compose down
