name: Test Django

on:
  pull_request:
    branches:
      - master

jobs:
  test-django:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=${{ secrets.NEXT_PUBLIC_SITE_BASE_DOMAIN }}" >> .env
          echo "SITE_DOMAIN=${{ secrets.SITE_DOMAIN }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Initialize ./django/static
        run: mkdir -p ./django/static

      - name: Build Docker containers
        run: |
          docker compose up --build -d

      - name: Run tests
        run: |
          echo "Tests or other tasks run here"

      - name: Bring down Docker containers
        run: docker compose down
